config/routes.rb
Rails.application.routes.draw do

  get 'static/about'

  get 'static/contact'

  root "welcome#index"

  devise_for :users

  resources :posts do
    resources :comments
  end

  get '/about' => 'static#about_us', as: "about_us"
  get '/contact' => 'static#contact_us', as: "contact_us"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :users
  belongs_to :posts
  belongs_to :courses
  belongs_to :lectures
end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :courses
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :users
  has_many :posts
  has_many :comments
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :users
  belongs_to :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def about_us
  end

  def contact_us
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @posts = Post.all.order("created_at DESC").limit(3)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <title>All for ITD Canada Students</title>
    <%= favicon_link_tag 'logo.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:900,100' rel='stylesheet' type='text/css'>
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <div class="wrapper">
    <header>
      <!--Navigation-->
      <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <p><%= link_to image_tag('logo.png', alt: "ITD canada logo"), root_path, class: 'navbar-brand' %></p>
        </div><!--/navbar-header-->

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "New Posts", new_post_path %></li>
            <li><%= link_to "About School", root_path %></li>
            <li><%= link_to "About Course", root_path %></li>
            <li><%= link_to "Projects", root_path %></li>
          </ul>
          <div class="navbar-right">
          <%= link_to "Log in", new_user_session_path, class: "sign-btn btn btn-default navbar-btn" %>
          <%= link_to "Sign up", new_user_registration_path, class: "sign-btn btn btn-default navbar-btn" %>
       </div>
        </div><!--/collapse -->
      </div><!--/container-->
    </nav>

  </header>



<%= yield %>



  <footer>
  <div class="container">
    <nav class="fnavi">
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", about_us_path %></li>
        <li><%= link_to "Contact Us", contact_us_path %></li>
      </ul>
    </nav>
    <small class="copyright text-center">Copyright ITD Students 2016</small>
  </div>
  </footer>

  </div><!--/wrapper-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/posts/home.html.erb
<!---Top Image-->
      <div class="jumbotron text-center">
      <div class="position-center">
      <h1>ALL FOR ITD STUDENTS</h1>
      <p>This website is for sharing information about ITD</p>
    </div>
    </div>

  <!--New Posts-->
  <div id="new-post" class="container">
  <div class="row">
  <section class="col-md-10 col-md-offset-1">
    <h2 class="text-center">New Posts</h2>
    <!--Each Posts-->
    <div class="post-box">
    <div class="media">
      <div class="media-left">
        <a href="#">
          <%= image_tag 'sample.jpg', class: "media-object img-rounded", alt: "face" %>
        </a>
      </div>
      <div class="media-body">
        <h3><a href="#">How can i make my student's card?</a></h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
        <span>Comments </span>
        <span> | </span>
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
        <span>2016.3.13.12:45</span>
      </div>
    </div>

    <div class="media">
      <div class="media-left">
        <a href="#">
          <%= image_tag 'sample.jpg', class: "media-object img-rounded", alt: "face" %>
        </a>
      </div>
      <div class="media-body">
        <h3><a href="#">How can i make my student's card?</a></h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
        <span>Comments </span>
        <span> | </span>
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
        <span>2016.3.13.12:45</span>
      </div>
    </div>

    </div><!--/post-box-->

    <nav class="center">
      <ul class="pagination">
        <li>
          <a href="#" aria-label="Previous">
            <span aria-hidsden="true">&laquo;</span>
          </a>
        </li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li>
          <a href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
  </section><!--/new-post-->
  </div><!--/row-->
  </div><!--/container-->

  <!--School Information-->
  <section id="school-information">
    <h2 class="text-center">School Information</h2>
    <div class="clearfix">
      <div class="each-information">
      <div class="each-box">
        <h3>ITD Life</h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting.Lorem Ipsum is simply dummy text of the printing and typesetting</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span></button>
      <div class="clear"></div>
      </div>
      </div>
      <div class="each-information">
        <h3>ITD Life</h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting.Lorem Ipsum is simply dummy text of the printing and typesetting</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span></button>
      <div class="clear"></div>
      </div>
      </div>
  </section>
  

  <!--Courses-->
  <section id="courses">
  <div class="container">
  <div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2 class="text-center">Courses</h2>
    <div class="row">
    <div class="each-course col-md-4 text-center">
      <p><a href="#"><%= image_tag 'icon.png', alt: 'IT', width: '100px', height: '100px' %></a></p>
      <h3><a href="#">IT</a></h3>
      <p>Lorem Ipsum is simply dummy text of the printing</p>
    </div>
    <div class="each-course col-md-4 text-center">
      <p><a href="#"><%= image_tag 'icon.png', alt: 'IT', width: '100px', height: '100px' %></a></p>
      <h3><a href="#">IT</a></h3>
      <p>Lorem Ipsum is simply dummy text of the printing</p>
    </div>
    <div class="each-course col-md-4 text-center">
      <p><a href="#"><%= image_tag 'icon.png', alt: 'IT', width: '100px', height: '100px' %></a></p>
      <h3><a href="#">IT</a></h3>
      <p>Lorem Ipsum is simply dummy text of the printing</p>
    </div>
    </div><!--/row-->


    <div class="row">
    <div class="each-course col-md-4 text-center">
      <p><a href="#"><%= image_tag 'icon.png', alt: 'IT', width: '100px', height: '100px' %></a></p>
      <h3><a href="#">IT</a></h3>
      <p>Lorem Ipsum is simply dummy text of the printing</p>
    </div>
    <div class="each-course col-md-4 text-center">
      <p><a href="#"><%= image_tag 'icon.png', alt: 'IT', width: '100px', height: '100px' %></a></p>
      <h3><a href="#">IT</a></h3>
      <p>Lorem Ipsum is simply dummy text of the printing</p>
    </div>
    </div><!--/row-->
  </div>
  </div><!--/row-->
  </div><!--/container-->
  </section>

  <section id="projects">
  <div class="container">
    <h2 class="text-center">Your Projects</h2>
    <div class="row">
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    </div><!--/row-->

    <nav>
      <ul class="pager">
        <li><a href="#">&lt; Previous</a></li>
        <li><a href="#">Next &gt;</a></li>
      </ul>
    </nav>
  </div><!--/container-->
  </section>

app/views/posts/new.html.erb
<br>
<br>
<br>
<h1>Post Somethig!</h1>

app/views/welcome/index.html.erb
<!---Top Image-->
      <div class="jumbotron text-center">
      <div class="position-center">
      <h1>ALL FOR ITD STUDENTS</h1>
      <p>This website is for sharing information about ITD</p>
    </div>
    </div>

  <!--New Posts-->
  <div id="new-post" class="container">
  <div class="row">
  <section class="col-md-10 col-md-offset-1">
    <h2 class="text-center">New Posts</h2>
    <!--Each Posts-->
    <div class="post-box">
    <div class="media">
      <div class="media-left">
        <a href="#">
          <%= image_tag 'sample.jpg', class: "media-object img-rounded", alt: "face" %>
        </a>
      </div>
      <div class="media-body">
        <h3><a href="#">How can i make my student's card?</a></h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
        <span>Comments </span>
        <span> | </span>
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
        <span>2016.3.13.12:45</span>
      </div>
    </div>

    <div class="media">
      <div class="media-left">
        <a href="#">
          <%= image_tag 'sample.jpg', class: "media-object img-rounded", alt: "face" %>
        </a>
      </div>
      <div class="media-body">
        <h3><a href="#">How can i make my student's card?</a></h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
        <span>Comments </span>
        <span> | </span>
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
        <span>2016.3.13.12:45</span>
      </div>
    </div>

    </div><!--/post-box-->

    <nav class="center">
      <ul class="pagination">
        <li>
          <a href="#" aria-label="Previous">
            <span aria-hidsden="true">&laquo;</span>
          </a>
        </li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li>
          <a href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
  </section><!--/new-post-->
  </div><!--/row-->
  </div><!--/container-->

  <!--School Information-->
  <section id="school-information">
    <h2 class="text-center">School Information</h2>
    <div class="clearfix">
      <div class="each-information">
      <div class="each-box">
        <h3>ITD Life</h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting.Lorem Ipsum is simply dummy text of the printing and typesetting</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span></button>
      <div class="clear"></div>
      </div>
      </div>
      <div class="each-information">
        <h3>ITD Life</h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting.Lorem Ipsum is simply dummy text of the printing and typesetting</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span></button>
      <div class="clear"></div>
      </div>
      </div>
  </section>
  

  <!--Courses-->
  <section id="courses">
  <div class="container">
  <div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2 class="text-center">Courses</h2>
    <div class="row">
    <div class="each-course col-md-4 text-center">
      <p><a href="#"><%= image_tag 'icon.png', alt: 'IT', width: '100px', height: '100px' %></a></p>
      <h3><a href="#">IT</a></h3>
      <p>Lorem Ipsum is simply dummy text of the printing</p>
    </div>
    <div class="each-course col-md-4 text-center">
      <p><a href="#"><%= image_tag 'icon.png', alt: 'IT', width: '100px', height: '100px' %></a></p>
      <h3><a href="#">IT</a></h3>
      <p>Lorem Ipsum is simply dummy text of the printing</p>
    </div>
    <div class="each-course col-md-4 text-center">
      <p><a href="#"><%= image_tag 'icon.png', alt: 'IT', width: '100px', height: '100px' %></a></p>
      <h3><a href="#">IT</a></h3>
      <p>Lorem Ipsum is simply dummy text of the printing</p>
    </div>
    </div><!--/row-->


    <div class="row">
    <div class="each-course col-md-4 text-center">
      <p><a href="#"><%= image_tag 'icon.png', alt: 'IT', width: '100px', height: '100px' %></a></p>
      <h3><a href="#">IT</a></h3>
      <p>Lorem Ipsum is simply dummy text of the printing</p>
    </div>
    <div class="each-course col-md-4 text-center">
      <p><a href="#"><%= image_tag 'icon.png', alt: 'IT', width: '100px', height: '100px' %></a></p>
      <h3><a href="#">IT</a></h3>
      <p>Lorem Ipsum is simply dummy text of the printing</p>
    </div>
    </div><!--/row-->
  </div>
  </div><!--/row-->
  </div><!--/container-->
  </section>

  <section id="projects">
  <div class="container">
    <h2 class="text-center">Your Projects</h2>
    <div class="row">
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    <div class="each-project col-md-4 text-center">
      <p><a href="#"><%= image_tag 'sample.jpg', alt: "IT", class: "img-responsive" %></a></p>
      <h3 class="title">Ikuto Portfolio</h3>
      <p class="name">Ikuto Itoko</p>
      <p class="description">Lorem Ipsum is simply dummy text of the printing.Lorem Ipsum is simply dummy text of the printingLorem Ipsum is simply dummy text of the printing</p>
      <button type="button" class="btn btn-default navbar-btn">More Detail</button>
    </div>
    </div><!--/row-->

    <nav>
      <ul class="pager">
        <li><a href="#">&lt; Previous</a></li>
        <li><a href="#">Next &gt;</a></li>
      </ul>
    </nav>
  </div><!--/container-->
  </section>